server:
  port: 8888
  tomcat:
    max-swallow-size: -1
    accept-count: 1000
    max-connections: 10000
    max-threads: 2000
    min-spare-threads: 50
  servlet:
    context-path: /wandering
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*


spring:
  profiles:
    #which profile to use
    active: dev